util: clarify error message in "wmaker.inst" in case of directory creation failure
Previously, the directory was expected to already exist, but as now it is
automatically created it is a good idea in case of problem to have the
message clearer.

Took opportunity to indent properly that part of code.

Signed-off-by: Christophe CURIS <christophe.curis@free.fr>

diff --git a/util/wmaker.inst.in b/util/wmaker.inst.in
--- a/util/wmaker.inst.in
+++ b/util/wmaker.inst.in
@@ -113,8 +113,8 @@ else
 	if [ ! -d "$GSDIR" ]; then
 		# in this case, and in this case only, mkdir needs -p option
 		mkdir -p $GSDIR || {
-		echo "Directory specified in GNUSTEP_USER_ROOT environment variable does not exist"
-		exit 1
+		    echo "Directory specified in GNUSTEP_USER_ROOT environment variable does not exist and could not be created"
+		    exit 1
 		}
 		chmod +rwx $GSDIR || exit 1
 	fi
